#!/usr/bin/env python3
"""Expand project-local C++ includes into one submission file."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


LOCAL_INCLUDE = re.compile(r'^\s*#\s*include\s*"([^"]+)"\s*(?://.*)?$')


class BundleError(RuntimeError):
    pass


class Bundler:
    def __init__(self, include_dirs: list[Path]) -> None:
        self.include_dirs = [path.resolve() for path in include_dirs]
        self.expanded: set[Path] = set()

    def display_name(self, source: Path) -> str:
        for root in self.include_dirs:
            try:
                return source.relative_to(root).as_posix()
            except ValueError:
                pass
        return source.name

    def resolve_include(self, name: str, including_file: Path) -> Path:
        candidates = [including_file.parent / name]
        candidates.extend(root / name for root in self.include_dirs)
        for candidate in candidates:
            resolved = candidate.resolve()
            if resolved.is_file():
                return resolved
        searched = "\n  ".join(str(path) for path in candidates)
        raise BundleError(
            f'cannot resolve local include "{name}" from {including_file}\n'
            f"searched:\n  {searched}"
        )

    def expand(self, source: Path) -> str:
        source = source.resolve()
        if source in self.expanded:
            return f"// already bundled: {source.name}\n"
        if not source.is_file():
            raise BundleError(f"input file does not exist: {source}")

        self.expanded.add(source)
        display_name = self.display_name(source)
        output: list[str] = [f"// BEGIN bundled file: {display_name}\n"]
        for line in source.read_text(encoding="utf-8").splitlines(keepends=True):
            match = LOCAL_INCLUDE.match(line.rstrip("\r\n"))
            if match is None:
                output.append(line)
                continue
            dependency = self.resolve_include(match.group(1), source)
            output.append(self.expand(dependency))
        output.append(f"// END bundled file: {display_name}\n")
        return "".join(output)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Expand quoted C++ includes and create one submit-ready file."
    )
    parser.add_argument("input", type=Path, help="entry C++ source")
    parser.add_argument("-o", "--output", required=True, type=Path)
    parser.add_argument(
        "-I",
        "--include-dir",
        action="append",
        default=[],
        type=Path,
        help="additional root for quoted includes (repeatable)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    entry = args.input.resolve()
    output = args.output.resolve()
    if entry == output:
        raise BundleError("input and output must be different files")

    kit_root = Path(__file__).resolve().parents[1]
    include_dirs = [entry.parent, kit_root, *args.include_dir]
    bundled = Bundler(include_dirs).expand(entry)
    banner = (
        "// Generated by ahc-precontest-kit/tools/bundle.py\n"
        "// Submit this file alone. Project-local includes are expanded below.\n\n"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(banner + bundled, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
